//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2021. 10. 29. 9:47:12
namespace Common.Models
{
    /// <summary>
    /// There are no comments for StudentSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("StudentSingle")]
    public partial class StudentSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Student>
    {
        /// <summary>
        /// Initialize a new StudentSingle object.
        /// </summary>
        public StudentSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new StudentSingle object.
        /// </summary>
        public StudentSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new StudentSingle object.
        /// </summary>
        public StudentSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Student> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Courses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Courses")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Common.Models.Course> Courses
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Courses == null))
                {
                    this._Courses = Context.CreateQuery<global::Common.Models.Course>(GetPath("Courses"));
                }
                return this._Courses;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Common.Models.Course> _Courses;
    }
    /// <summary>
    /// There are no comments for Student in the schema.
    /// </summary>
    /// <KeyProperties>
    /// StudentId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("StudentId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Student")]
    public partial class Student : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Student object.
        /// </summary>
        /// <param name="studentId">Initial value of StudentId.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="dayOfBirth">Initial value of DayOfBirth.</param>
        /// <param name="neptun">Initial value of Neptun.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Student CreateStudent(int studentId, string name, string dayOfBirth, string neptun)
        {
            Student student = new Student();
            student.StudentId = studentId;
            student.Name = name;
            student.DayOfBirth = dayOfBirth;
            student.Neptun = neptun;
            return student;
        }
        /// <summary>
        /// There are no comments for Property StudentId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("StudentId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "StudentId is required.")]
        public virtual int StudentId
        {
            get
            {
                return this._StudentId;
            }
            set
            {
                this.OnStudentIdChanging(value);
                this._StudentId = value;
                this.OnStudentIdChanged();
                this.OnPropertyChanged("StudentId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _StudentId;
        partial void OnStudentIdChanging(int value);
        partial void OnStudentIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Name is required.")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property DayOfBirth in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DayOfBirth")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "DayOfBirth is required.")]
        public virtual string DayOfBirth
        {
            get
            {
                return this._DayOfBirth;
            }
            set
            {
                this.OnDayOfBirthChanging(value);
                this._DayOfBirth = value;
                this.OnDayOfBirthChanged();
                this.OnPropertyChanged("DayOfBirth");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DayOfBirth;
        partial void OnDayOfBirthChanging(string value);
        partial void OnDayOfBirthChanged();
        /// <summary>
        /// There are no comments for Property Neptun in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Neptun")]
        [global::System.ComponentModel.DataAnnotations.StringLengthAttribute(6, ErrorMessage = "Neptun cannot be longer than 6 characters.")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Neptun is required.")]
        public virtual string Neptun
        {
            get
            {
                return this._Neptun;
            }
            set
            {
                this.OnNeptunChanging(value);
                this._Neptun = value;
                this.OnNeptunChanged();
                this.OnPropertyChanged("Neptun");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Neptun;
        partial void OnNeptunChanging(string value);
        partial void OnNeptunChanged();
        /// <summary>
        /// There are no comments for Property Courses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Courses")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Common.Models.Course> Courses
        {
            get
            {
                return this._Courses;
            }
            set
            {
                this.OnCoursesChanging(value);
                this._Courses = value;
                this.OnCoursesChanged();
                this.OnPropertyChanged("Courses");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Common.Models.Course> _Courses = new global::Microsoft.OData.Client.DataServiceCollection<global::Common.Models.Course>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnCoursesChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Common.Models.Course> value);
        partial void OnCoursesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CourseSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CourseSingle")]
    public partial class CourseSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Course>
    {
        /// <summary>
        /// Initialize a new CourseSingle object.
        /// </summary>
        public CourseSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CourseSingle object.
        /// </summary>
        public CourseSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CourseSingle object.
        /// </summary>
        public CourseSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Course> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Subject in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Subject")]
        public virtual global::Common.Models.SubjectSingle Subject
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Subject == null))
                {
                    this._Subject = new global::Common.Models.SubjectSingle(this.Context, GetPath("Subject"));
                }
                return this._Subject;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Common.Models.SubjectSingle _Subject;
        /// <summary>
        /// There are no comments for Students in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Students")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Common.Models.Student> Students
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Students == null))
                {
                    this._Students = Context.CreateQuery<global::Common.Models.Student>(GetPath("Students"));
                }
                return this._Students;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Common.Models.Student> _Students;
    }
    /// <summary>
    /// There are no comments for Course in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CourseId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("CourseId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Course")]
    public partial class Course : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Course object.
        /// </summary>
        /// <param name="courseId">Initial value of CourseId.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="type">Initial value of Type.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Course CreateCourse(int courseId, string name, string type)
        {
            Course course = new Course();
            course.CourseId = courseId;
            course.Name = name;
            course.Type = type;
            return course;
        }
        /// <summary>
        /// There are no comments for Property CourseId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CourseId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "CourseId is required.")]
        public virtual int CourseId
        {
            get
            {
                return this._CourseId;
            }
            set
            {
                this.OnCourseIdChanging(value);
                this._CourseId = value;
                this.OnCourseIdChanged();
                this.OnPropertyChanged("CourseId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _CourseId;
        partial void OnCourseIdChanging(int value);
        partial void OnCourseIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        [global::System.ComponentModel.DataAnnotations.StringLengthAttribute(100, ErrorMessage = "Name cannot be longer than 100 characters.")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Name is required.")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Type")]
        [global::System.ComponentModel.DataAnnotations.StringLengthAttribute(10, ErrorMessage = "Type cannot be longer than 10 characters.")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Type is required.")]
        public virtual string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Day in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Day")]
        public virtual global::System.Nullable<int> Day
        {
            get
            {
                return this._Day;
            }
            set
            {
                this.OnDayChanging(value);
                this._Day = value;
                this.OnDayChanged();
                this.OnPropertyChanged("Day");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _Day;
        partial void OnDayChanging(global::System.Nullable<int> value);
        partial void OnDayChanged();
        /// <summary>
        /// There are no comments for Property From in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("From")]
        public virtual string From
        {
            get
            {
                return this._From;
            }
            set
            {
                this.OnFromChanging(value);
                this._From = value;
                this.OnFromChanged();
                this.OnPropertyChanged("From");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _From;
        partial void OnFromChanging(string value);
        partial void OnFromChanged();
        /// <summary>
        /// There are no comments for Property To in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("To")]
        public virtual string To
        {
            get
            {
                return this._To;
            }
            set
            {
                this.OnToChanging(value);
                this._To = value;
                this.OnToChanged();
                this.OnPropertyChanged("To");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _To;
        partial void OnToChanging(string value);
        partial void OnToChanged();
        /// <summary>
        /// There are no comments for Property Subject in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Subject")]
        public virtual global::Common.Models.Subject Subject
        {
            get
            {
                return this._Subject;
            }
            set
            {
                this.OnSubjectChanging(value);
                this._Subject = value;
                this.OnSubjectChanged();
                this.OnPropertyChanged("Subject");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Common.Models.Subject _Subject;
        partial void OnSubjectChanging(global::Common.Models.Subject value);
        partial void OnSubjectChanged();
        /// <summary>
        /// There are no comments for Property Students in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Students")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Common.Models.Student> Students
        {
            get
            {
                return this._Students;
            }
            set
            {
                this.OnStudentsChanging(value);
                this._Students = value;
                this.OnStudentsChanged();
                this.OnPropertyChanged("Students");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Common.Models.Student> _Students = new global::Microsoft.OData.Client.DataServiceCollection<global::Common.Models.Student>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnStudentsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Common.Models.Student> value);
        partial void OnStudentsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for SubjectSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("SubjectSingle")]
    public partial class SubjectSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Subject>
    {
        /// <summary>
        /// Initialize a new SubjectSingle object.
        /// </summary>
        public SubjectSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new SubjectSingle object.
        /// </summary>
        public SubjectSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new SubjectSingle object.
        /// </summary>
        public SubjectSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Subject> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Courses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Courses")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Common.Models.Course> Courses
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Courses == null))
                {
                    this._Courses = Context.CreateQuery<global::Common.Models.Course>(GetPath("Courses"));
                }
                return this._Courses;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Common.Models.Course> _Courses;
    }
    /// <summary>
    /// There are no comments for Subject in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SubjectId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("SubjectId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Subject")]
    public partial class Subject : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Subject object.
        /// </summary>
        /// <param name="subjectId">Initial value of SubjectId.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Subject CreateSubject(int subjectId, string name)
        {
            Subject subject = new Subject();
            subject.SubjectId = subjectId;
            subject.Name = name;
            return subject;
        }
        /// <summary>
        /// There are no comments for Property SubjectId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SubjectId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "SubjectId is required.")]
        public virtual int SubjectId
        {
            get
            {
                return this._SubjectId;
            }
            set
            {
                this.OnSubjectIdChanging(value);
                this._SubjectId = value;
                this.OnSubjectIdChanged();
                this.OnPropertyChanged("SubjectId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _SubjectId;
        partial void OnSubjectIdChanging(int value);
        partial void OnSubjectIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        [global::System.ComponentModel.DataAnnotations.StringLengthAttribute(100, ErrorMessage = "Name cannot be longer than 100 characters.")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Name is required.")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Courses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Courses")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Common.Models.Course> Courses
        {
            get
            {
                return this._Courses;
            }
            set
            {
                this.OnCoursesChanging(value);
                this._Courses = value;
                this.OnCoursesChanged();
                this.OnPropertyChanged("Courses");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Common.Models.Course> _Courses = new global::Microsoft.OData.Client.DataServiceCollection<global::Common.Models.Course>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnCoursesChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Common.Models.Course> value);
        partial void OnCoursesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AttendanceSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("AttendanceSingle")]
    public partial class AttendanceSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Attendance>
    {
        /// <summary>
        /// Initialize a new AttendanceSingle object.
        /// </summary>
        public AttendanceSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new AttendanceSingle object.
        /// </summary>
        public AttendanceSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new AttendanceSingle object.
        /// </summary>
        public AttendanceSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Attendance> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Course in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Course")]
        public virtual global::Common.Models.CourseSingle Course
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Course == null))
                {
                    this._Course = new global::Common.Models.CourseSingle(this.Context, GetPath("Course"));
                }
                return this._Course;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Common.Models.CourseSingle _Course;
        /// <summary>
        /// There are no comments for Student in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Student")]
        public virtual global::Common.Models.StudentSingle Student
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Student == null))
                {
                    this._Student = new global::Common.Models.StudentSingle(this.Context, GetPath("Student"));
                }
                return this._Student;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Common.Models.StudentSingle _Student;
    }
    /// <summary>
    /// There are no comments for Attendance in the schema.
    /// </summary>
    /// <KeyProperties>
    /// AttendanceId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("AttendanceId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Attendance")]
    public partial class Attendance : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Attendance object.
        /// </summary>
        /// <param name="attendanceId">Initial value of AttendanceId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Attendance CreateAttendance(int attendanceId)
        {
            Attendance attendance = new Attendance();
            attendance.AttendanceId = attendanceId;
            return attendance;
        }
        /// <summary>
        /// There are no comments for Property AttendanceId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AttendanceId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "AttendanceId is required.")]
        public virtual int AttendanceId
        {
            get
            {
                return this._AttendanceId;
            }
            set
            {
                this.OnAttendanceIdChanging(value);
                this._AttendanceId = value;
                this.OnAttendanceIdChanged();
                this.OnPropertyChanged("AttendanceId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _AttendanceId;
        partial void OnAttendanceIdChanging(int value);
        partial void OnAttendanceIdChanged();
        /// <summary>
        /// There are no comments for Property CourseId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CourseId")]
        public virtual global::System.Nullable<int> CourseId
        {
            get
            {
                return this._CourseId;
            }
            set
            {
                this.OnCourseIdChanging(value);
                this._CourseId = value;
                this.OnCourseIdChanged();
                this.OnPropertyChanged("CourseId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _CourseId;
        partial void OnCourseIdChanging(global::System.Nullable<int> value);
        partial void OnCourseIdChanged();
        /// <summary>
        /// There are no comments for Property StudentId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("StudentId")]
        public virtual global::System.Nullable<int> StudentId
        {
            get
            {
                return this._StudentId;
            }
            set
            {
                this.OnStudentIdChanging(value);
                this._StudentId = value;
                this.OnStudentIdChanged();
                this.OnPropertyChanged("StudentId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _StudentId;
        partial void OnStudentIdChanging(global::System.Nullable<int> value);
        partial void OnStudentIdChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Date")]
        public virtual string Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
                this.OnPropertyChanged("Date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Date;
        partial void OnDateChanging(string value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property CheckInTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CheckInTime")]
        public virtual string CheckInTime
        {
            get
            {
                return this._CheckInTime;
            }
            set
            {
                this.OnCheckInTimeChanging(value);
                this._CheckInTime = value;
                this.OnCheckInTimeChanged();
                this.OnPropertyChanged("CheckInTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _CheckInTime;
        partial void OnCheckInTimeChanging(string value);
        partial void OnCheckInTimeChanged();
        /// <summary>
        /// There are no comments for Property CheckOutTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CheckOutTime")]
        public virtual string CheckOutTime
        {
            get
            {
                return this._CheckOutTime;
            }
            set
            {
                this.OnCheckOutTimeChanging(value);
                this._CheckOutTime = value;
                this.OnCheckOutTimeChanged();
                this.OnPropertyChanged("CheckOutTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _CheckOutTime;
        partial void OnCheckOutTimeChanging(string value);
        partial void OnCheckOutTimeChanged();
        /// <summary>
        /// There are no comments for Property Course in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Course")]
        public virtual global::Common.Models.Course Course
        {
            get
            {
                return this._Course;
            }
            set
            {
                this.OnCourseChanging(value);
                this._Course = value;
                this.OnCourseChanged();
                this.OnPropertyChanged("Course");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Common.Models.Course _Course;
        partial void OnCourseChanging(global::Common.Models.Course value);
        partial void OnCourseChanged();
        /// <summary>
        /// There are no comments for Property Student in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Student")]
        public virtual global::Common.Models.Student Student
        {
            get
            {
                return this._Student;
            }
            set
            {
                this.OnStudentChanging(value);
                this._Student = value;
                this.OnStudentChanged();
                this.OnPropertyChanged("Student");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Common.Models.Student _Student;
        partial void OnStudentChanging(global::Common.Models.Student value);
        partial void OnStudentChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::Common.Models.Student as global::Common.Models.StudentSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Common.Models.StudentSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Common.Models.Student> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Common.Models.StudentSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Common.Models.Student as global::Common.Models.StudentSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="studentId">The value of studentId</param>
        public static global::Common.Models.StudentSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Common.Models.Student> _source,
            int studentId)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "StudentId", studentId }
            };
            return new global::Common.Models.StudentSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Common.Models.Course as global::Common.Models.CourseSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Common.Models.CourseSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Common.Models.Course> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Common.Models.CourseSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Common.Models.Course as global::Common.Models.CourseSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="courseId">The value of courseId</param>
        public static global::Common.Models.CourseSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Common.Models.Course> _source,
            int courseId)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "CourseId", courseId }
            };
            return new global::Common.Models.CourseSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Common.Models.Subject as global::Common.Models.SubjectSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Common.Models.SubjectSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Common.Models.Subject> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Common.Models.SubjectSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Common.Models.Subject as global::Common.Models.SubjectSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="subjectId">The value of subjectId</param>
        public static global::Common.Models.SubjectSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Common.Models.Subject> _source,
            int subjectId)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "SubjectId", subjectId }
            };
            return new global::Common.Models.SubjectSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Common.Models.Attendance as global::Common.Models.AttendanceSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Common.Models.AttendanceSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Common.Models.Attendance> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Common.Models.AttendanceSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Common.Models.Attendance as global::Common.Models.AttendanceSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="attendanceId">The value of attendanceId</param>
        public static global::Common.Models.AttendanceSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Common.Models.Attendance> _source,
            int attendanceId)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "AttendanceId", attendanceId }
            };
            return new global::Common.Models.AttendanceSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
    }
}
namespace Microsoft.AspNetCore.Mvc
{
    /// <summary>
    /// There are no comments for FileContentResult in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("FileContentResult")]
    public partial class FileContentResult : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new FileContentResult object.
        /// </summary>
        /// <param name="enableRangeProcessing">Initial value of EnableRangeProcessing.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static FileContentResult CreateFileContentResult(bool enableRangeProcessing)
        {
            FileContentResult fileContentResult = new FileContentResult();
            fileContentResult.EnableRangeProcessing = enableRangeProcessing;
            return fileContentResult;
        }
        /// <summary>
        /// There are no comments for Property FileContents in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FileContents")]
        public virtual byte[] FileContents
        {
            get
            {
                return this._FileContents;
            }
            set
            {
                this.OnFileContentsChanging(value);
                this._FileContents = value;
                this.OnFileContentsChanged();
                this.OnPropertyChanged("FileContents");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private byte[] _FileContents;
        partial void OnFileContentsChanging(byte[] value);
        partial void OnFileContentsChanged();
        /// <summary>
        /// There are no comments for Property FileDownloadName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FileDownloadName")]
        public virtual string FileDownloadName
        {
            get
            {
                return this._FileDownloadName;
            }
            set
            {
                this.OnFileDownloadNameChanging(value);
                this._FileDownloadName = value;
                this.OnFileDownloadNameChanged();
                this.OnPropertyChanged("FileDownloadName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _FileDownloadName;
        partial void OnFileDownloadNameChanging(string value);
        partial void OnFileDownloadNameChanged();
        /// <summary>
        /// There are no comments for Property LastModified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LastModified")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> LastModified
        {
            get
            {
                return this._LastModified;
            }
            set
            {
                this.OnLastModifiedChanging(value);
                this._LastModified = value;
                this.OnLastModifiedChanged();
                this.OnPropertyChanged("LastModified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _LastModified;
        partial void OnLastModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnLastModifiedChanged();
        /// <summary>
        /// There are no comments for Property EntityTag in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("EntityTag")]
        public virtual global::Microsoft.Net.Http.Headers.EntityTagHeaderValue EntityTag
        {
            get
            {
                return this._EntityTag;
            }
            set
            {
                this.OnEntityTagChanging(value);
                this._EntityTag = value;
                this.OnEntityTagChanged();
                this.OnPropertyChanged("EntityTag");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Net.Http.Headers.EntityTagHeaderValue _EntityTag;
        partial void OnEntityTagChanging(global::Microsoft.Net.Http.Headers.EntityTagHeaderValue value);
        partial void OnEntityTagChanged();
        /// <summary>
        /// There are no comments for Property EnableRangeProcessing in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("EnableRangeProcessing")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "EnableRangeProcessing is required.")]
        public virtual bool EnableRangeProcessing
        {
            get
            {
                return this._EnableRangeProcessing;
            }
            set
            {
                this.OnEnableRangeProcessingChanging(value);
                this._EnableRangeProcessing = value;
                this.OnEnableRangeProcessingChanged();
                this.OnPropertyChanged("EnableRangeProcessing");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private bool _EnableRangeProcessing;
        partial void OnEnableRangeProcessingChanging(bool value);
        partial void OnEnableRangeProcessingChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
namespace Microsoft.Net.Http.Headers
{
    /// <summary>
    /// There are no comments for EntityTagHeaderValue in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("EntityTagHeaderValue")]
    public partial class EntityTagHeaderValue : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
namespace Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot) :
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Microsoft.Net.Http.Headers", "Microsoft.Net.Http.Headers");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Microsoft.AspNetCore.Mvc", "Microsoft.AspNetCore.Mvc");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Common.Models", "Common.Models");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("Microsoft.Net.Http.Headers", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Microsoft.Net.Http.Headers.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Microsoft.Net.Http.Headers.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Microsoft.AspNetCore.Mvc", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Microsoft.AspNetCore.Mvc.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Microsoft.AspNetCore.Mvc.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Common.Models", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Common.Models.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Common.Models.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Students in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Students")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Common.Models.Student> Students
        {
            get
            {
                if ((this._Students == null))
                {
                    this._Students = base.CreateQuery<global::Common.Models.Student>("Students");
                }
                return this._Students;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Common.Models.Student> _Students;
        /// <summary>
        /// There are no comments for Courses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Courses")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Common.Models.Course> Courses
        {
            get
            {
                if ((this._Courses == null))
                {
                    this._Courses = base.CreateQuery<global::Common.Models.Course>("Courses");
                }
                return this._Courses;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Common.Models.Course> _Courses;
        /// <summary>
        /// There are no comments for Subjects in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Subjects")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Common.Models.Subject> Subjects
        {
            get
            {
                if ((this._Subjects == null))
                {
                    this._Subjects = base.CreateQuery<global::Common.Models.Subject>("Subjects");
                }
                return this._Subjects;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Common.Models.Subject> _Subjects;
        /// <summary>
        /// There are no comments for Attendances in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Attendances")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Common.Models.Attendance> Attendances
        {
            get
            {
                if ((this._Attendances == null))
                {
                    this._Attendances = base.CreateQuery<global::Common.Models.Attendance>("Attendances");
                }
                return this._Attendances;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Common.Models.Attendance> _Attendances;
        /// <summary>
        /// There are no comments for Students in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToStudents(global::Common.Models.Student student)
        {
            base.AddObject("Students", student);
        }
        /// <summary>
        /// There are no comments for Courses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToCourses(global::Common.Models.Course course)
        {
            base.AddObject("Courses", course);
        }
        /// <summary>
        /// There are no comments for Subjects in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToSubjects(global::Common.Models.Subject subject)
        {
            base.AddObject("Subjects", subject);
        }
        /// <summary>
        /// There are no comments for Attendances in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToAttendances(global::Common.Models.Attendance attendance)
        {
            base.AddObject("Attendances", attendance);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private const string filePath = @"OData ServiceCsdl.xml";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader();
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, true, out edmModel, out errors))
                    {
	                    global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();
	                    foreach (var error in errors)
	                    {
		                    errorMessages.Append(error.ErrorMessage);
		                    errorMessages.Append("; ");
	                    }
	                    throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader()
            {
                try
                {
                    var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();
                    var resourcePath = global::System.Linq.Enumerable.Single(assembly.GetManifestResourceNames(), str => str.EndsWith(filePath));
                    global::System.IO.Stream stream = assembly.GetManifestResourceStream(resourcePath);
                    return global::System.Xml.XmlReader.Create(new global::System.IO.StreamReader(stream));
                }
                catch(global::System.Xml.XmlException e)
                {
                    throw new global::System.Xml.XmlException("Failed to create an XmlReader from the stream. Check if the resource exists.", e);
                }
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// There are no comments for GetQRCode in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("GetQRCode")]
        public static global::Microsoft.OData.Client.DataServiceQuerySingle<global::Microsoft.AspNetCore.Mvc.FileContentResult> GetQRCode(this global::Microsoft.OData.Client.DataServiceQuery<global::Common.Models.Student> _source, int studentId)
        {
            if (!_source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return _source.CreateFunctionQuerySingle<global::Microsoft.AspNetCore.Mvc.FileContentResult>("Default.GetQRCode", false, new global::Microsoft.OData.Client.UriOperationParameter("studentId", studentId));
        }
    }
}
